# Generated by Django 6.0.5 on 2026-05-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_dashboard", "0002_ridestream"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="weather_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
