# Generated by Django 6.0.5 on 2026-05-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_dashboard", "0003_ride_weather_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="distance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
