# Generated by Django 6.0.5 on 2026-05-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0004_ride_distance_ride_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='elapsed_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
