# Generated by Django 6.0.5 on 2026-05-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_dashboard", "0005_ride_elapsed_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="ridestream",
            name="avg_headwind",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
