# Generated by Django 6.0.5 on 2026-05-31 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_auth", "0001_initial"),
        ("app_dashboard", "0006_ridestream_avg_headwind"),
        ("app_maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="athlete",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rides",
                to="app_auth.stravaprofile",
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="bike",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rides",
                to="app_maintenance.bike",
            ),
        ),
    ]
