# Generated by Django 6.0.5 on 2026-08-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_dashboard", "0007_ride_athlete_ride_bike"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="ai_summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ride",
            name="ai_summary_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
