# Generated by Django 6.0.5 on 2026-08-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_dashboard", "0008_ride_ai_summary_ride_ai_summary_generated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="wear_impact_generated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Zeitpunkt der letzten Generierung von wear_impact_summary.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="wear_impact_summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Zwischengespeicherte KI-Erklaerung (Deutsch) des Verschleiss-Anteils dieser Fahrt.",
            ),
        ),
    ]
