# Generated by Django 6.0.5 on 2026-05-31 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("drivetrain", "Antrieb"),
                            ("brakes", "Bremsen"),
                            ("wheels", "Laufräder"),
                            ("suspension", "Federung"),
                            ("cockpit", "Cockpit"),
                            ("frame", "Rahmen & Lager"),
                            ("electric", "E-Antrieb"),
                            ("lighting", "Beleuchtung"),
                            ("other", "Sonstiges"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "applicable_bike_types",
                    models.JSONField(
                        default=list,
                        help_text="Liste von BikeType-Keys. Leer = gilt für alle.",
                    ),
                ),
                (
                    "warn_km",
                    models.FloatField(
                        blank=True, help_text="Warnung nach X km", null=True
                    ),
                ),
                (
                    "warn_hours",
                    models.FloatField(
                        blank=True, help_text="Warnung nach X Fahrstunden", null=True
                    ),
                ),
                (
                    "warn_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Warnung nach X Tagen (Kalender)",
                        null=True,
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=True,
                        help_text="True = aus Fixture, False = vom User angelegt",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Bike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strava_bike_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "bike_type",
                    models.CharField(
                        choices=[
                            ("road", "Rennrad"),
                            ("mtb", "Mountainbike"),
                            ("gravel", "Gravel"),
                            ("ebike_road", "E-Rennrad"),
                            ("ebike_mtb", "E-MTB"),
                            ("ebike_city", "E-Stadtrad"),
                            ("city", "Stadtrad"),
                            ("cx", "Cyclocross"),
                            ("other", "Sonstiges"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("retired", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bikes",
                        to="app_auth.stravaprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ComponentSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_name", models.CharField(blank=True, max_length=100)),
                (
                    "bike",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="app_maintenance.bike",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="slots",
                        to="app_maintenance.componenttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["template__category", "template__name"],
                "unique_together": {("bike", "template")},
            },
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                (
                    "distance_at_install",
                    models.FloatField(
                        blank=True,
                        help_text="Km-Stand des Fahrrads beim Einbau",
                        null=True,
                    ),
                ),
                ("installed_at", models.DateField(blank=True, null=True)),
                (
                    "retired_at",
                    models.DateField(
                        blank=True,
                        help_text="Datum des Ausbaus / Entsorgung",
                        null=True,
                    ),
                ),
                ("is_mounted", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="app_maintenance.componentslot",
                    ),
                ),
            ],
            options={
                "ordering": ["-installed_at"],
            },
        ),
    ]
