# Generated by Django 6.0.5 on 2026-07-07 18:31

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_maintenance", "0002_load_component_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="custom_warn_days",
            field=models.IntegerField(
                blank=True, help_text="Individuelle Lebensdauer in Tagen", null=True
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="custom_warn_km",
            field=models.FloatField(
                blank=True, help_text="Individuelle Lebensdauer in km", null=True
            ),
        ),
        migrations.AddField(
            model_name="componenttemplate",
            name="supports_condition_estimate",
            field=models.BooleanField(
                default=True,
                help_text="Ob eine prozentuale Zustandsschätzung sinnvoll ist (z.B. nein bei Lagern/Services).",
            ),
        ),
        migrations.CreateModel(
            name="ComponentCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checked_at", models.DateField(default=datetime.date.today)),
                (
                    "checked_at_distance_km",
                    models.FloatField(
                        blank=True,
                        help_text="Km-Stand des Fahrrads zum Zeitpunkt der Prüfung",
                        null=True,
                    ),
                ),
                (
                    "condition_pct",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Geschätzter Restzustand in %, nur falls vom Komponententyp unterstützt",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "snooze_km",
                    models.FloatField(
                        blank=True,
                        help_text="Erneut warnen nach X weiteren km ab checked_at_distance_km",
                        null=True,
                    ),
                ),
                (
                    "snooze_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Erneut warnen nach X weiteren Tagen ab checked_at",
                        null=True,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="app_maintenance.component",
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_at", "-id"],
            },
        ),
    ]
