# Generated by Django 6.0.5 on 2026-08-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_maintenance", "0004_update_supports_condition_estimate"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherSensitivityCoefficient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("drivetrain", "Antrieb"),
                            ("brakes", "Bremsen"),
                            ("wheels", "Laufräder"),
                            ("suspension", "Federung"),
                            ("cockpit", "Cockpit"),
                            ("frame", "Rahmen & Lager"),
                            ("electric", "E-Antrieb"),
                            ("lighting", "Beleuchtung"),
                            ("other", "Sonstiges"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "rain_sensitivity",
                    models.FloatField(
                        default=0.0,
                        help_text="Gewichtung des Regen-Faktors (0 = kein Effekt).",
                    ),
                ),
                (
                    "heat_sensitivity",
                    models.FloatField(
                        default=0.0,
                        help_text="Gewichtung des Hitze-Faktors (0 = kein Effekt).",
                    ),
                ),
                (
                    "cold_sensitivity",
                    models.FloatField(
                        default=0.0,
                        help_text="Gewichtung des Kälte-Faktors (0 = kein Effekt).",
                    ),
                ),
                (
                    "wind_sensitivity",
                    models.FloatField(
                        default=0.0,
                        help_text="Gewichtung des Wind-Faktors (0 = kein Effekt). Bewusst konservativ, da der Wind-Mechanismus für mechanischen Verschleiß physikalisch schwach ist.",
                    ),
                ),
                (
                    "last_calibrated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Zeitpunkt der letzten Kalibrierung aus echten Nutzerdaten. Null = es gilt noch der Heuristik-Default.",
                        null=True,
                    ),
                ),
                (
                    "calibration_sample_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Anzahl Datenpunkte der letzten Kalibrierung. Null = noch nie kalibriert.",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Begründung/Quelle der aktuellen Werte.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Wetter-Sensitivitäts-Koeffizient",
                "verbose_name_plural": "Wetter-Sensitivitäts-Koeffizienten",
                "ordering": ["category"],
            },
        ),
        migrations.AddField(
            model_name="component",
            name="weather_wear_computed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Zeitpunkt der letzten Neuberechnung von weather_wear_km.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="weather_wear_explanation",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Zwischengespeicherte KI-generierte Erklärung (Deutsch) der Wetter-Verschleiß-Zahlen.",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="weather_wear_explanation_generated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Zeitpunkt der letzten KI-Erklärung-Generierung. Wird gegen weather_wear_computed_at verglichen, um die Erklärung bei neuen Zahlen ungültig zu machen.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="weather_wear_km",
            field=models.FloatField(
                blank=True,
                help_text="Wetter-gewichteter Verschleiß in km seit Einbau, inkl. Zuschlägen für Regen/Hitze/Kälte/Wind. Wird asynchron per Celery-Task neu berechnet, nicht live pro Request.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="weather_wear_ride_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Anzahl der in die letzte Berechnung einbezogenen Fahrten seit Einbau — dient als Konfidenz-Indikator (wenige Fahrten = wenig aussagekräftiger Wert).",
                null=True,
            ),
        ),
    ]
