# Generated by Django 6.0.5 on 2026-08-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_maintenance", "0006_seed_weather_sensitivity_coefficients"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentcheck",
            name="checked_at_weather_wear_km",
            field=models.FloatField(
                blank=True,
                help_text="component.weather_wear_km zum Zeitpunkt der Prüfung — Baseline, damit der wetterbereinigte Warn-Status nach einer Freigabe ebenfalls zurückgesetzt wird (analog zu checked_at_distance_km für die km-Achse).",
                null=True,
            ),
        ),
    ]
