# Generated by Django 6.0.5 on 2026-08-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_maintenance", "0007_componentcheck_checked_at_weather_wear_km"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bike",
            name="bike_type",
            field=models.CharField(
                choices=[
                    ("road", "Rennrad"),
                    ("mtb", "Mountainbike"),
                    ("gravel", "Gravel"),
                    ("ebike_road", "E-Rennrad"),
                    ("ebike_mtb", "E-MTB"),
                    ("ebike_city", "E-Stadtrad"),
                    ("city", "Stadtrad"),
                    ("cx", "Cyclocross"),
                    ("triathlon", "Triathlon/Zeitfahrrad"),
                    ("other", "Sonstiges"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
