# Generated by Django 6.0.5 on 2026-08-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_maintenance", "0008_alter_bike_bike_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="bike",
            name="condition_report",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Zwischengespeicherte KI-generierte Zusammenfassung (Deutsch) des Gesamtzustands des Bikes.",
            ),
        ),
        migrations.AddField(
            model_name="bike",
            name="condition_report_generated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Zeitpunkt der letzten Zustandsbericht-Generierung.",
                null=True,
            ),
        ),
    ]
