# Generated by Django 6.0.5 on 2026-08-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_maintenance", "0009_bike_condition_report_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componenttemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("drivetrain", "Antrieb"),
                    ("brakes", "Bremsen"),
                    ("wheels", "Laufräder"),
                    ("suspension", "Federung"),
                    ("cockpit", "Cockpit"),
                    ("frame", "Rahmen & Lager"),
                    ("electric", "E-Antrieb"),
                    ("lighting", "Beleuchtung"),
                    ("accessories", "Zubehör"),
                    ("other", "Sonstiges"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="weathersensitivitycoefficient",
            name="category",
            field=models.CharField(
                choices=[
                    ("drivetrain", "Antrieb"),
                    ("brakes", "Bremsen"),
                    ("wheels", "Laufräder"),
                    ("suspension", "Federung"),
                    ("cockpit", "Cockpit"),
                    ("frame", "Rahmen & Lager"),
                    ("electric", "E-Antrieb"),
                    ("lighting", "Beleuchtung"),
                    ("accessories", "Zubehör"),
                    ("other", "Sonstiges"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
