# Generated by Django 6.0.5 on 2026-08-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_maintenance", "0011_add_more_component_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="check_instructions",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Zwischengespeicherte KI-generierte Prüfanleitung (Deutsch) für diese Komponente.",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="check_instructions_generated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Zeitpunkt der letzten Prüfanleitung-Generierung.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="check_instructions_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="warn_status_overall zum Zeitpunkt der letzten Anleitung-Generierung.",
                max_length=20,
            ),
        ),
    ]
