# Generated by Django 6.0.5 on 2026-08-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_maintenance", "0012_component_check_instructions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bike",
            name="predicted_unsafe_notified_for_date",
            field=models.DateField(
                blank=True,
                help_text="Vorhergesagtes Next-Ride-Datum, fuer das zuletzt eine Vorhersage-Warn-E-Mail verschickt wurde.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="last_warn_notified_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="warn_status_overall zum Zeitpunkt der letzten Warn-E-Mail.",
                max_length=20,
            ),
        ),
    ]
