# Generated by Django 6.0.5 on 2026-08-31 17:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_maintenance", "0014_component_group_and_wheel_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceInterval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("chain_lube", "Kettenschmierung"),
                            ("sealant", "Tubeless-Dichtmilch"),
                            ("brake_bleed", "Bremse entlüften"),
                            ("di2_charge", "Schaltungs-Akku laden"),
                            ("battery", "Batterie/Akku"),
                            ("custom", "Sonstiges"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("interval_km", models.FloatField(blank=True, null=True)),
                ("interval_days", models.IntegerField(blank=True, null=True)),
                ("last_done_at", models.DateField(blank=True, null=True)),
                (
                    "last_done_distance_km",
                    models.FloatField(
                        blank=True,
                        help_text="Km-Stand des Bikes bei der letzten Erledigung.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Wartungs-Intervall",
                "verbose_name_plural": "Wartungs-Intervalle",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("done_at", models.DateField(default=datetime.date.today)),
                ("done_distance_km", models.FloatField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-done_at", "-id"],
            },
        ),
        migrations.AlterModelOptions(
            name="componentgroup",
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.AlterUniqueTogether(
            name="componentslot",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="componentgroup",
            name="applicable_bike_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste von BikeType-Keys. Leer = gilt für alle.",
            ),
        ),
        migrations.AddField(
            model_name="componentgroup",
            name="category",
            field=models.CharField(
                choices=[
                    ("drivetrain", "Antrieb"),
                    ("brakes", "Bremsen"),
                    ("wheels", "Laufräder"),
                    ("suspension", "Federung"),
                    ("cockpit", "Cockpit"),
                    ("frame", "Rahmen & Lager"),
                    ("electric", "E-Antrieb"),
                    ("lighting", "Beleuchtung"),
                    ("accessories", "Zubehör"),
                    ("other", "Sonstiges"),
                ],
                default="other",
                help_text="Bestimmt Icon/Farbe/Sortierung in der UI.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="componentgroup",
            name="is_system",
            field=models.BooleanField(
                default=True,
                help_text="True = aus Migration/Seed, False = vom User angelegt.",
            ),
        ),
        migrations.AddField(
            model_name="componentgroup",
            name="recommended",
            field=models.BooleanField(
                default=True,
                help_text="Im geführten Stepper für ein neues Bike vorausgewählt.",
            ),
        ),
        migrations.AddField(
            model_name="componentgroup",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="componenttemplate",
            name="default_in_group",
            field=models.BooleanField(
                default=True,
                help_text="Im Baugruppen-Dialog vorausgewählt (seltene Teile: False).",
            ),
        ),
        migrations.AddField(
            model_name="componenttemplate",
            name="maintenance_kind",
            field=models.CharField(
                choices=[
                    ("part", "Verschleißteil"),
                    ("consumable", "Verbrauchsmaterial / Pflege"),
                ],
                default="part",
                help_text="PART = physisches Verschleißteil (Slot + Component). CONSUMABLE = Verbrauchsmaterial/Pflege, wird als MaintenanceInterval getrackt statt als Component.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BikeAssembly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Anzeigename, Default = group.name. Editierbar (z.B. 'Sommer-LRS').",
                        max_length=100,
                    ),
                ),
                (
                    "installed_at",
                    models.DateField(
                        blank=True,
                        help_text="Wann diese Baugruppe (zuletzt komplett) montiert wurde.",
                        null=True,
                    ),
                ),
                ("retired_at", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bike",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assemblies",
                        to="app_maintenance.bike",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="app_maintenance.componentgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Baugruppe (Bike-Instanz)",
                "verbose_name_plural": "Baugruppen (Bike-Instanzen)",
                "ordering": ["group__sort_order", "group__name", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="componentslot",
            name="assembly",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="app_maintenance.bikeassembly",
            ),
        ),
        migrations.AddConstraint(
            model_name="componentslot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("assembly__isnull", False)),
                fields=("assembly", "template"),
                name="uniq_assembly_template",
            ),
        ),
        migrations.AddConstraint(
            model_name="componentslot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("assembly__isnull", True)),
                fields=("bike", "template"),
                name="uniq_bike_template_ungrouped",
            ),
        ),
        migrations.AddField(
            model_name="maintenanceinterval",
            name="assembly",
            field=models.ForeignKey(
                blank=True,
                help_text="Optionale Zuordnung zu einer Baugruppe (z.B. Dichtmilch → Laufrad).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intervals",
                to="app_maintenance.bikeassembly",
            ),
        ),
        migrations.AddField(
            model_name="maintenanceinterval",
            name="bike",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intervals",
                to="app_maintenance.bike",
            ),
        ),
        migrations.AddField(
            model_name="maintenanceinterval",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Herkunfts-Vorlage (maintenance_kind=CONSUMABLE), falls aus Katalog.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intervals",
                to="app_maintenance.componenttemplate",
            ),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="interval",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="app_maintenance.maintenanceinterval",
            ),
        ),
    ]
