# Generated by Django 6.0.5 on 2026-09-01 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_maintenance", "0017_backfill_bike_assemblies"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="distance_at_retire",
            field=models.FloatField(
                blank=True,
                help_text="Km-Stand des Fahrrads beim Ausbau. Nötig, um ein mitten in einer Baugruppen-Nutzungsperiode getauschtes Teil sauber abzuschneiden (siehe AssemblyUsagePeriod).",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AssemblyUsagePeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateField(help_text="Tag der Montage.")),
                (
                    "started_distance_km",
                    models.FloatField(
                        blank=True,
                        help_text="Km-Stand des Bikes bei der Montage.",
                        null=True,
                    ),
                ),
                (
                    "ended_at",
                    models.DateField(
                        blank=True,
                        help_text="Tag des Abziehens. None = aktuell montiert.",
                        null=True,
                    ),
                ),
                (
                    "ended_distance_km",
                    models.FloatField(
                        blank=True,
                        help_text="Km-Stand des Bikes beim Abziehen.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assembly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="app_maintenance.bikeassembly",
                    ),
                ),
            ],
            options={
                "verbose_name": "Baugruppen-Nutzungszeitraum",
                "verbose_name_plural": "Baugruppen-Nutzungszeiträume",
                "ordering": ["started_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["assembly", "ended_at"],
                        name="app_mainten_assembl_4d1e11_idx",
                    )
                ],
            },
        ),
    ]
