# Generated by Django 6.0.5 on 2026-09-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_maintenance", "0020_move_cassette_to_rear_wheel"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="carried_over_wear_km",
            field=models.FloatField(
                blank=True,
                help_text="Verschleiß-km, die bereits vor einem früheren Ausbau aufgelaufen waren. Wird beim Reaktivieren eines ausgebauten Teils (siehe api/views.py::_build_assembly_from_request, reuse_component_id) einmalig eingefroren, weil die neue Nutzungsperiode/Baugruppe die alte Fahrhistorie sonst nicht sieht — component_active_km() rechnet ja nur die Perioden der aktuellen Baugruppe. compute_wear() addiert diesen Wert auf den frisch berechneten km-Verschleiß.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="carried_over_weather_wear_km",
            field=models.FloatField(
                blank=True,
                help_text="Analog zu carried_over_wear_km, aber für die wetter-gewichtete Achse: friert weather_wear_km beim Reaktivieren ein, damit WeatherWearService.recompute_component() den alten Wert nicht durch die neue (kürzere) Fahrhistorie überschreibt statt ihn draufzurechnen.",
                null=True,
            ),
        ),
    ]
