from django.urls import path

from .views import (
    AssemblyActivateView,
    AssemblyRetireView,
    AssemblySwapView,
    AssistantModelsView,
    AssistantSetupView,
    BikeAssemblyDetailView,
    BikeAssemblyListView,
    BikeConditionReportView,
    BikeDetailView,
    BikeDistanceAtDateView,
    BikeListView,
    ComponentCheckInstructionsView,
    ComponentCheckView,
    ComponentDetailView,
    ComponentGroupListView,
    ComponentListView,
    ComponentSlotDetailView,
    ComponentSlotListView,
    ComponentTemplateDetailView,
    ComponentTemplateListView,
    ComponentWeatherExplanationView,
    MaintenanceIntervalDetailView,
    MaintenanceIntervalListCreateView,
    MaintenanceIntervalLogView,
    SlotMountView,
    SlotUnmountView,
)

urlpatterns = [
    path("maintenance/bikes/", BikeListView.as_view(), name="bike-list"),
    path("maintenance/bikes/<int:pk>/", BikeDetailView.as_view(), name="bike-detail"),
    path(
        "maintenance/bikes/<int:bike_id>/distance-at/",
        BikeDistanceAtDateView.as_view(),
        name="bike-distance-at",
    ),
    path("maintenance/groups/", ComponentGroupListView.as_view(), name="group-list"),
    # "Kudo" — KI-Assistent fuers Bike-Anlegen (siehe api/bike_assistant.py)
    path(
        "maintenance/assistant/models/",
        AssistantModelsView.as_view(),
        name="assistant-models",
    ),
    path(
        "maintenance/bikes/<int:bike_id>/assistant/setup/",
        AssistantSetupView.as_view(),
        name="assistant-setup",
    ),
    path(
        "maintenance/bikes/<int:bike_id>/assemblies/",
        BikeAssemblyListView.as_view(),
        name="assembly-list",
    ),
    path(
        "maintenance/assemblies/<int:pk>/",
        BikeAssemblyDetailView.as_view(),
        name="assembly-detail",
    ),
    path(
        "maintenance/assemblies/<int:pk>/activate/",
        AssemblyActivateView.as_view(),
        name="assembly-activate",
    ),
    path(
        "maintenance/assemblies/<int:pk>/retire/",
        AssemblyRetireView.as_view(),
        name="assembly-retire",
    ),
    path(
        "maintenance/assemblies/<int:pk>/swap/",
        AssemblySwapView.as_view(),
        name="assembly-swap",
    ),
    path(
        "maintenance/bikes/<int:bike_id>/intervals/",
        MaintenanceIntervalListCreateView.as_view(),
        name="interval-create",
    ),
    path(
        "maintenance/intervals/<int:pk>/",
        MaintenanceIntervalDetailView.as_view(),
        name="interval-detail",
    ),
    path(
        "maintenance/intervals/<int:pk>/log/",
        MaintenanceIntervalLogView.as_view(),
        name="interval-log",
    ),
    path(
        "maintenance/bikes/<int:pk>/condition-report/",
        BikeConditionReportView.as_view(),
        name="bike-condition-report",
    ),
    path(
        "maintenance/bikes/<int:bike_id>/slots/",
        ComponentSlotListView.as_view(),
        name="slot-list",
    ),
    path(
        "maintenance/slots/<int:pk>/",
        ComponentSlotDetailView.as_view(),
        name="slot-detail",
    ),
    path(
        "maintenance/slots/<int:pk>/mount/", SlotMountView.as_view(), name="slot-mount"
    ),
    path(
        "maintenance/slots/<int:pk>/unmount/",
        SlotUnmountView.as_view(),
        name="slot-unmount",
    ),
    path(
        "maintenance/slots/<int:slot_id>/components/",
        ComponentListView.as_view(),
        name="component-list",
    ),
    path(
        "maintenance/components/<int:pk>/",
        ComponentDetailView.as_view(),
        name="component-detail",
    ),
    path(
        "maintenance/components/<int:pk>/check/",
        ComponentCheckView.as_view(),
        name="component-check",
    ),
    path(
        "maintenance/components/<int:pk>/weather-explanation/",
        ComponentWeatherExplanationView.as_view(),
        name="component-weather-explanation",
    ),
    path(
        "maintenance/components/<int:pk>/check-instructions/",
        ComponentCheckInstructionsView.as_view(),
        name="component-check-instructions",
    ),
    path(
        "maintenance/templates/",
        ComponentTemplateListView.as_view(),
        name="template-list",
    ),
    path(
        "maintenance/templates/<int:pk>/",
        ComponentTemplateDetailView.as_view(),
        name="template-detail",
    ),
]
