# Generated by Django 6.0.5 on 2026-07-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stravaprofile",
            name="last_sync_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stravaprofile",
            name="sync_error",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="stravaprofile",
            name="sync_finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stravaprofile",
            name="sync_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stravaprofile",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("idle", "idle"),
                    ("running", "running"),
                    ("success", "success"),
                    ("error", "error"),
                ],
                default="idle",
                max_length=10,
            ),
        ),
    ]
