# Generated by Django 6.0.5 on 2026-08-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_auth", "0002_stravaprofile_last_sync_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stravaprofile",
            name="sync_task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="stravaprofile",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("idle", "idle"),
                    ("running", "running"),
                    ("success", "success"),
                    ("error", "error"),
                    ("cancelled", "cancelled"),
                ],
                default="idle",
                max_length=10,
            ),
        ),
    ]
