# Generated by Django 6.0.5 on 2026-08-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_auth", "0003_stravaprofile_sync_task_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stravaprofile",
            name="sync_progress_current",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stravaprofile",
            name="sync_progress_total",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
