# Generated by Django 6.0.5 on 2026-08-07 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_auth", "0004_stravaprofile_sync_progress_current_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stravaprofile",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="stravaprofile",
            name="lastname",
        ),
    ]
