# Generated by Django 6.0.5 on 2026-08-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_auth", "0005_remove_stravaprofile_firstname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stravaprofile",
            name="email_notifications_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Kill-Switch fuer Warn-/Vorhersage-/Willkommens-E-Mails. Nur per Admin togglebar.",
            ),
        ),
        migrations.AddField(
            model_name="stravaprofile",
            name="welcome_email_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Zeitpunkt des letzten Versands der Willkommens-E-Mail — automatisch gesetzt bei Erstanmeldung, erneut auslösbar über die Admin-Action 'Willkommens-E-Mail senden'.",
                null=True,
            ),
        ),
    ]
