# Generated by Django 6.0.5 on 2026-08-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_auth", "0006_stravaprofile_email_notifications_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stravaprofile",
            name="email_notifications_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Kill-Switch fuer Warn-/Vorhersage-/Willkommens-E-Mails.",
            ),
        ),
    ]
